# MODEL
HIDDEN_LAYER_NODE_NUMBER = 256
D_INPUT_LAYER_NODE_NUMBER = 28 * 28
D_HIDDEN_LAYER_NUMBER = 2
G_INPUT_LAYER_NODE_NUMBER = 128
G_HIDDEN_LAYER_NUMBER = 2

# LEARNING
DROPOUT_RATE = 0.5
EPOCH_NUMBER = 10000
BATCH_SIZE = 100
LEARNING_RATE = 1e-4
K = 1
